//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP.CE.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBP.CE.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercedes-Benz.
        /// </summary>
        public static string ApplicationCopyright {
            get {
                return ResourceManager.GetString("ApplicationCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Certificates.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baumuster.
        /// </summary>
        public static string Baumuster {
            get {
                return ResourceManager.GetString("Baumuster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???????????????????????.
        /// </summary>
        public static string BuyAndDeliveryQuestion {
            get {
                return ResourceManager.GetString("BuyAndDeliveryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy-Back Contract.
        /// </summary>
        public static string BuyBackContract {
            get {
                return ResourceManager.GetString("BuyBackContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CAE {
            get {
                return ResourceManager.GetString("CAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save password.
        /// </summary>
        public static string CannotSavePassword {
            get {
                return ResourceManager.GetString("CannotSavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarSelection card name.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBCertified card name.
        /// </summary>
        public static string CardNameMB {
            get {
                return ResourceManager.GetString("CardNameMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used1 card name.
        /// </summary>
        public static string CardNameUsed1 {
            get {
                return ResourceManager.GetString("CardNameUsed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type.
        /// </summary>
        public static string CertificateType {
            get {
                return ResourceManager.GetString("CertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was successfully changed.
        /// </summary>
        public static string ChangePasswordSucessful {
            get {
                return ResourceManager.GetString("ChangePasswordSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Search.
        /// </summary>
        public static string ClientSearch {
            get {
                return ResourceManager.GetString("ClientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common User.
        /// </summary>
        public static string CommonUser {
            get {
                return ResourceManager.GetString("CommonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string ConfirmVehicleInfo {
            get {
                return ResourceManager.GetString("ConfirmVehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Requests.
        /// </summary>
        public static string CorrectionRequests {
            get {
                return ResourceManager.GetString("CorrectionRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string County {
            get {
                return ResourceManager.GetString("County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateCertificate {
            get {
                return ResourceManager.GetString("CreateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Client.
        /// </summary>
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create vehicle.
        /// </summary>
        public static string CreateVehicle {
            get {
                return ResourceManager.GetString("CreateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponibility.
        /// </summary>
        public static string Disponibility {
            get {
                return ResourceManager.GetString("Disponibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditClient.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable vehicle.
        /// </summary>
        public static string EnableVehicle {
            get {
                return ResourceManager.GetString("EnableVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Number.
        /// </summary>
        public static string EngineNo {
            get {
                return ResourceManager.GetString("EngineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise.
        /// </summary>
        public static string Enterprise {
            get {
                return ResourceManager.GetString("Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving new password.
        /// </summary>
        public static string ErrorSavingNewPassword {
            get {
                return ResourceManager.GetString("ErrorSavingNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when trying to send new password. Try again please..
        /// </summary>
        public static string ErrorSendNewPassword {
            get {
                return ResourceManager.GetString("ErrorSendNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing.
        /// </summary>
        public static string Financing {
            get {
                return ResourceManager.GetString("Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give vehicle.
        /// </summary>
        public static string GiveVehicle {
            get {
                return ResourceManager.GetString("GiveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicapped with higher degree of disability of 60%?.
        /// </summary>
        public static string HandicapedQuestion {
            get {
                return ResourceManager.GetString("HandicapedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided user name or password is incorrect..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity id.
        /// </summary>
        public static string InvalidEntityId {
            get {
                return ResourceManager.GetString("InvalidEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entity type.
        /// </summary>
        public static string InvalidEntityType {
            get {
                return ResourceManager.GetString("InvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komission.
        /// </summary>
        public static string Komission {
            get {
                return ResourceManager.GetString("Komission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessee.
        /// </summary>
        public static string Lessee {
            get {
                return ResourceManager.GetString("Lessee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Issue Date.
        /// </summary>
        public static string LicenseIssueDate {
            get {
                return ResourceManager.GetString("LicenseIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        public static string LicenseNo {
            get {
                return ResourceManager.GetString("LicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string LicenseType {
            get {
                return ResourceManager.GetString("LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open/Close menu.
        /// </summary>
        public static string MenuToggle {
            get {
                return ResourceManager.GetString("MenuToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage (MB Certified).
        /// </summary>
        public static string MileageMBCertified {
            get {
                return ResourceManager.GetString("MileageMBCertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage (StarSelection).
        /// </summary>
        public static string MileageStarSelection {
            get {
                return ResourceManager.GetString("MileageStarSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage (Used1).
        /// </summary>
        public static string MileageUsed1 {
            get {
                return ResourceManager.GetString("MileageUsed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIF.
        /// </summary>
        public static string NIF {
            get {
                return ResourceManager.GetString("NIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIPC.
        /// </summary>
        public static string NIPC {
            get {
                return ResourceManager.GetString("NIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string NoteConfirmVehicleInfo {
            get {
                return ResourceManager.GetString("NoteConfirmVehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Keys.
        /// </summary>
        public static string NumberOfKeys {
            get {
                return ResourceManager.GetString("NumberOfKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add one email and one phone.
        /// </summary>
        public static string OneEmailAndOnePhone {
            get {
                return ResourceManager.GetString("OneEmailAndOnePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Client was successfully saved.
        /// </summary>
        public static string operationResultModalSuccessMessage {
            get {
                return ResourceManager.GetString("operationResultModalSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Client.
        /// </summary>
        public static string operationResultModalTitle {
            get {
                return ResourceManager.GetString("operationResultModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet.
        /// </summary>
        public static string Outlet {
            get {
                return ResourceManager.GetString("Outlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Type.
        /// </summary>
        public static string OwnerType {
            get {
                return ResourceManager.GetString("OwnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle already has an pending correction request.
        /// </summary>
        public static string PendingCorrectionRequestExists {
            get {
                return ResourceManager.GetString("PendingCorrectionRequestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string PendingRequests {
            get {
                return ResourceManager.GetString("PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign.
        /// </summary>
        public static string Reassign {
            get {
                return ResourceManager.GetString("Reassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Vehicle.
        /// </summary>
        public static string ReassignVehicle {
            get {
                return ResourceManager.GetString("ReassignVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Data Clean.
        /// </summary>
        public static string RequestDataClean {
            get {
                return ResourceManager.GetString("RequestDataClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestDate.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password id required..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string RequiredUser {
            get {
                return ResourceManager.GetString("RequiredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Vehicle.
        /// </summary>
        public static string SearchVehicle {
            get {
                return ResourceManager.GetString("SearchVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type vehicle identification number to find vehicle.
        /// </summary>
        public static string SearchVehicleHeaderDescription {
            get {
                return ResourceManager.GetString("SearchVehicleHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send password.
        /// </summary>
        public static string SendPassword {
            get {
                return ResourceManager.GetString("SendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string SignInTop {
            get {
                return ResourceManager.GetString("SignInTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Off.
        /// </summary>
        public static string SignOff {
            get {
                return ResourceManager.GetString("SignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Use.
        /// </summary>
        public static string SpecialUse {
            get {
                return ResourceManager.GetString("SpecialUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarSelection.
        /// </summary>
        public static string StarSelection {
            get {
                return ResourceManager.GetString("StarSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuinte.
        /// </summary>
        public static string Taxpayer {
            get {
                return ResourceManager.GetString("Taxpayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type.
        /// </summary>
        public static string TransportType {
            get {
                return ResourceManager.GetString("TransportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Address.
        /// </summary>
        public static string TypeOfAddress {
            get {
                return ResourceManager.GetString("TypeOfAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Vehicle.
        /// </summary>
        public static string TypeOfVehicle {
            get {
                return ResourceManager.GetString("TypeOfVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error.
        /// </summary>
        public static string UnspecifiedError {
            get {
                return ResourceManager.GetString("UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manual.
        /// </summary>
        public static string UserManual {
            get {
                return ResourceManager.GetString("UserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle with the identification number {{chassis}}, license number {{license}}, is already assigned at {{outletname}}..
        /// </summary>
        public static string VehicleAlreadyAssigned {
            get {
                return ResourceManager.GetString("VehicleAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Details.
        /// </summary>
        public static string VehicleDetails {
            get {
                return ResourceManager.GetString("VehicleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle is not available..
        /// </summary>
        public static string VehicleNotAvailable {
            get {
                return ResourceManager.GetString("VehicleNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Search.
        /// </summary>
        public static string VehicleSearch {
            get {
                return ResourceManager.GetString("VehicleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        public static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate will be issued without license..
        /// </summary>
        public static string WarningNoLicense {
            get {
                return ResourceManager.GetString("WarningNoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty End Date.
        /// </summary>
        public static string WarrantyEndDate {
            get {
                return ResourceManager.GetString("WarrantyEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Remarks.
        /// </summary>
        public static string WarrantyRemarks {
            get {
                return ResourceManager.GetString("WarrantyRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty Start Date.
        /// </summary>
        public static string WarrantyStartDate {
            get {
                return ResourceManager.GetString("WarrantyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong old password.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
